site_name: Cerebrate Project Documentation - doc.cerebrate-project.org
site_url: https://doc.cerebrate-project.org
repo_url: https://github.com/cerebrate-project/doc.cerebrate-project.org
edit_uri: edit/main/docs/

theme:
    name: material
    logo: assets/logo/logo.svg
    features:
        - navigation.tabs
        - navigation.tracking
        - search.highlight
        - search.share
plugins:
  - social:
      cards_color:
        fill: "#0FF1CE" 
        text: "#FFFFFF"
  - search
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  homepage: https://www.cerebrate-project.org/
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/cerebrateproje1
copyright: Copyright &copy; 2021 - 2022 Cerebrate Project 
